sudo:          false
language:      node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm test
#   TODO: figure out why gulp started failing (most likely related to dependency version change)
#   - gulp
cache:
  directories:
    - node_modules
