sudo:          false
language:      node_js
node_js:
  - "node"
install:
  - sudo apt-get install -y build-essential python
  - npm install
script:
  - npm test
  - gulp
cache:
  directories:
    - node_modules
